// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoNjeXo6U4NR5DzQ1aNGMDQNl19Egim5o',
    appId: '1:1050634742312:web:ea395003a4a45f0a73231d',
    messagingSenderId: '1050634742312',
    projectId: 'flutter-handbook-7b5d8',
    authDomain: 'flutter-handbook-7b5d8.firebaseapp.com',
    storageBucket: 'flutter-handbook-7b5d8.firebasestorage.app',
    measurementId: 'G-WXY1QK6P91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK_gbnp--EoB0aqBi92uR2vcQNRImw8cw',
    appId: '1:1050634742312:android:b542a969365dc30f73231d',
    messagingSenderId: '1050634742312',
    projectId: 'flutter-handbook-7b5d8',
    storageBucket: 'flutter-handbook-7b5d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsMCMe1rMO6f66y6IGrzHH8k9DS3re2hg',
    appId: '1:1050634742312:ios:f2964f1a046dfa9e73231d',
    messagingSenderId: '1050634742312',
    projectId: 'flutter-handbook-7b5d8',
    storageBucket: 'flutter-handbook-7b5d8.firebasestorage.app',
    iosBundleId: 'com.example.flutterHandbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsMCMe1rMO6f66y6IGrzHH8k9DS3re2hg',
    appId: '1:1050634742312:ios:f2964f1a046dfa9e73231d',
    messagingSenderId: '1050634742312',
    projectId: 'flutter-handbook-7b5d8',
    storageBucket: 'flutter-handbook-7b5d8.firebasestorage.app',
    iosBundleId: 'com.example.flutterHandbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoNjeXo6U4NR5DzQ1aNGMDQNl19Egim5o',
    appId: '1:1050634742312:web:e15ba8682d87da9173231d',
    messagingSenderId: '1050634742312',
    projectId: 'flutter-handbook-7b5d8',
    authDomain: 'flutter-handbook-7b5d8.firebaseapp.com',
    storageBucket: 'flutter-handbook-7b5d8.firebasestorage.app',
    measurementId: 'G-C2L0RG9NWJ',
  );
}
